config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :teams
  resources :matches
  root to: 'visitors#index'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :teams
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :teams
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :player
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  def index
    @matches = Match.all
    @teams = Team.all
  end

  def show
    @match = Match.find(params[:id])
    @home = Team.find(@match.home_team_id)
    @away = Team.find(@match.away_team_id)
  end

  def new
    @match = Match.new
    @teams = Team.all
  end

  def edit
  end

  def create
    @match = Match.new(match_params)
    # @team1 = Team.where(name: params[:match][:home_team][:name]).first_or_create
    # @team2 = Team.where(name: params[:match][:away_team][:name]).first_or_create

    # @match.teams << @team1
    # @match.teams << @team2
    # @match.home_team_id = @team1.id
    # @match.away_team_id = @team2.id

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_match
      @match = Match.find(params[:id])
    end

    def match_params
      params.require(:match).permit(:date, :value1, :value2, :home_team_id, :away_team_id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all
  end

  def show
  end

  def new
    @player = Player.new
  end

  def edit
  end

  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :role, :teams_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def show
  end

  def new
    @team = Team.new
  end

  def edit
  end

  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Instatscout'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Instatscout'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/matches/_form.html.slim
= simple_form_for(@match) do |f|
  = f.error_notification

  .form-inputs
    h4 Select Teams
    .form-group
      = f.select :home_team_id,
        options_for_select(@teams.map{|home| ["#{home.name}", home.id]}, f.object.home_team_id), {}, class: "form-control", :prompt => "Select a home team"
      = f.select :away_team_id,
        options_for_select(@teams.map{|away| ["#{away.name}", away.id]}, f.object.away_team_id), {}, class: "form-control", :prompt => "Select a away team"
    = f.input :date
    h4 Score
    .score
      p
        = f.input_field :value1, class: "form-control"
      p
        = f.input_field :value2, class: "form-control"

  .form-actions
    = f.button :submit
    = link_to 'Back', matches_path, class: 'btn btn-info', id: 'back_button'

app/views/matches/edit.html.slim
h1 Editing match

== render 'form'

= link_to 'Show', @match
'|
= link_to 'Back', matches_path

app/views/matches/index.html.slim
.container
  h1 Listing matches

  table
    thead
      tr.row_spasing
        th Match
        th Teams
        th Data
        th Score
        th
        th
        th

    tbody
      - @matches.each do |match|
        tr
          td = link_to "Match ##{match.id}", match_path(match)
          td #{@teams.find(match.home_team_id).name} - #{@teams.find(match.away_team_id).name}
          td = match.date.to_s(:short)
          td #{match.value1} - #{match.value2}

  br

  = link_to 'New Match', new_match_path, class: 'btn btn-info'

app/views/matches/new.html.slim
.container
  h1 New match

  == render 'form'

  

app/views/matches/show.html.slim
.container
  .row.text-center
    h1 #{@home.name} - #{@away.name}
    .col-md-6
      h4
        | HOME TEAM
      h1.team-name
        = link_to "#{@home.name}", team_path
      h1 #{@match.value1}
    .col-md-6
      h4
        | AWAY TEAM
      h1.team-name
        = link_to "#{@away.name}", team_path
      h1 #{@match.value2}
    h1
      = @match.date.to_s(:short)
    br
    = link_to 'Back', matches_path, class: 'btn btn-info'

app/views/players/_form.html.slim
= simple_form_for(@player) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :role
    = f.collection_select :teams_id, Team.order(:name), :id, :name, {include_blank: 'Select a Team'}, {class: "form-control"}
    br
  .form-actions
    = f.button :submit
    = link_to 'Back', players_path, class: 'btn btn-info', id: 'back_button'

app/views/players/edit.html.slim
.container
  h1 Editing player

  == render 'form'

app/views/players/index.html.slim
.container
  h1 Listing players

  table
    thead
      tr
        th Name
        th Role
        th Teams
        th
        th
        th

    tbody
      - @players.each do |player|
        tr.row_spasing
          td = player.name
          td = player.role
          td = player.teams.try(:name)
          td = link_to 'Show', player, class: 'btn btn-success'
          td = link_to 'Edit', edit_player_path(player), class: 'btn btn-warning', id: 'back_button'
          td = link_to 'Destroy', player, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger', id: 'back_button'

  br

  = link_to 'New Player', new_player_path, class: 'btn btn-info'

app/views/players/new.html.slim
.container
  h1 New player

  == render 'form'

app/views/players/show.html.slim
.container
  br
  h4
    strong Name:
    = @player.name
  br
  h4
    strong Role:
    = @player.role
  br
  h4
    strong Teams:
    = @player.teams_id
  br
  = link_to 'Edit', edit_player_path(@player), class: 'btn btn-warning'
  = link_to 'Back', players_path, class: 'btn btn-info', id: 'back_button'

app/views/visitors/index.html.erb
<h3>Welcome</h3>